// Fourtis-style banner TEMPLATE compositor. An admin uploads a designed
// artwork (illustration/3D mascot/etc — the thing code can't draw) via
// @dexvraadminbot; every listing/trending channel post then composites the
// token's logo into the artwork's logo spot (circle-clipped) plus an optional
// $TICKER + name overlay. This is exactly how fourtis produces the banners the
// operator considers good — the art is designed once, the code only pastes.
//
// No template uploaded → compose() returns null and callers fall back to the
// programmatic dynamic banner (bannerRender.js). Never throws.
const path = require("node:path");
const fss = require("node:fs");
const { loadJSONSync, saveJSON, DATA_DIR } = require("./helpers/persist");
const log = require("./helpers/logger");

const CONFIG_FILE = "bannerTemplate.json";
const KINDS = ["listing", "trending", "banner"];
// Reference canvas — every layout coordinate in this module assumes this space.
const REF_W = 2560;
const REF_H = 1280;
// Admin-uploaded artwork (wins) lives in DATA_DIR; a bundled default artwork
// ships in assets/ (generated by scripts/gen-artwork.mjs) so banners look
// designed out-of-the-box. BANNER_BUNDLED_DIR is overridable for tests.
const uploadedPath = (kind) => path.join(DATA_DIR, `banner-template-${kind}.png`);
const BUNDLED_DIR = process.env.BANNER_BUNDLED_DIR || path.join(__dirname, "..", "assets");
const bundledPath = (kind) => path.join(BUNDLED_DIR, `banner-artwork-${kind}.png`);

const exists = (p) => {
  try {
    return fss.existsSync(p) && fss.statSync(p).size > 0;
  } catch {
    return false;
  }
};

// ── Admin-uploaded GIF / VIDEO override (per kind) ───────────────────────────
// When set, the channel post uses this ANIMATED media instead of the composited
// still — a generic hype clip (the per-token details live in the caption, so
// nothing is composited into a video). Kind here is free-form (listing /
// trending / banner / pump) so pump alerts can carry a clip too.
const MEDIA_EXT = { gif: "animation", mp4: "video", webm: "video", mov: "video" };
function mediaPath(kind, ext) {
  return path.join(DATA_DIR, `banner-media-${kind}.${ext}`);
}
/** { type: 'animation'|'video', source } for a kind's uploaded clip, or null. */
function mediaOverride(kind) {
  for (const [ext, type] of Object.entries(MEDIA_EXT)) {
    const p = mediaPath(kind, ext);
    if (exists(p)) return { type, source: p };
  }
  return null;
}
async function saveMedia(kind, buffer, ext) {
  const e = String(ext || "mp4").toLowerCase();
  if (!MEDIA_EXT[e]) throw new Error(`unsupported media type .${e} (use gif/mp4/webm/mov)`);
  await removeMedia(kind); // one clip per kind — drop any prior ext
  await fss.promises.mkdir(DATA_DIR, { recursive: true });
  await fss.promises.writeFile(mediaPath(kind, e), buffer);
  return { type: MEDIA_EXT[e], ext: e };
}
async function removeMedia(kind) {
  for (const ext of Object.keys(MEDIA_EXT)) {
    try {
      await fss.promises.unlink(mediaPath(kind, ext));
    } catch {
      /* not present */
    }
  }
}
const hasMedia = (kind) => !!mediaOverride(kind);

// Defaults are tuned for the BUNDLED artworks (2560×1280). listing/trending:
// circular logo spot in the glowing ring + $TICKER/name under the status pill.
// banner (ads): a rectangular slot in the glass frame for the advertiser's
// creative, no text overlay (the creative speaks for itself).
const BASE_DEFAULTS = {
  slotShape: "circle", // "circle" (token logo) | "rect" (ad creative)
  logoSize: 420, // circle: diameter of the clipped logo
  logoX: 1890, // number | "center" — top-left of the slot
  logoY: 410,
  slotW: 1680, // rect: slot width/height
  slotH: 800,
  showText: true, // draw $TICKER + name overlay
  tickerFontSize: 96,
  tickerX: 210, // number | "center"
  tickerY: 618,
  tickerColor: "#FFFFFF",
  nameFontSize: 48,
  nameColor: "#B8CCC8",
  nameOffsetY: 96,
  // token meta chips (CHAIN · price · MC) inside the glass panel, under the
  // name — filled by live data. metaX = LEFT edge (or "center").
  metaX: 210,
  metaY: 772,
  metaFontSize: 34,
  // small badge on the glass pedestal under the ring (tier / trending duration)
  badgeX: 2100, // center x
  badgeY: 1002,
  badgeFontSize: 30,
};
const KIND_DEFAULTS = {
  listing: { ...BASE_DEFAULTS, tickerGlow: "#4EE6A8" },
  trending: { ...BASE_DEFAULTS, tickerGlow: "#38D8F0" },
  banner: { ...BASE_DEFAULTS, slotShape: "rect", logoX: 836, logoY: 296, slotW: 1548, slotH: 760, showText: false },
};
const defaultsFor = (kind) => KIND_DEFAULTS[kind] || BASE_DEFAULTS;
const DEFAULTS = BASE_DEFAULTS; // back-compat export

// Layout-version gate. updateSettings used to bake the ENTIRE then-current
// defaults into the saved file, so one ±20px tap froze every coordinate of
// that era's artwork forever — later default retunes could never win (live
// incident: ticker rendered at the bottom edge, empty text panel). Saved
// layouts now carry the version they were tuned against; a mismatch means
// "tuned for an older artwork" and the saved layout is ignored wholesale.
// Bump ONLY when the bundled artwork's layout changes (it invalidates saved
// admin tweaks by design — they were positioned against the old art).
const LAYOUT_VERSION = 6; // v6 artwork (gen-artwork.mjs)

function savedLayout(saved, kind) {
  const s = saved[kind];
  return s && s.layoutVersion === LAYOUT_VERSION ? s : {};
}

function loadConfig() {
  const saved = loadJSONSync(CONFIG_FILE, {});
  const out = {};
  for (const k of KINDS) out[k] = { ...defaultsFor(k), ...savedLayout(saved, k) };
  return out;
}

// ── Global ON/OFF switch (admin-bot controlled, persisted) ──────────────────
// Lives in the config file under `_global` so operators flip it from
// @dexvraadminbot instead of fighting .env/PM2 env-snapshot semantics (live
// incident 2026-07-19: a stale POST_BANNERS=0 survived every restart). The
// POST_BANNERS env is only the DEFAULT when no admin choice was saved.
function postingEnabled() {
  const g = loadJSONSync(CONFIG_FILE, {})._global || {};
  // Default ON — banners are a core feature. ONLY an explicit admin toggle
  // (persisted _global.enabled === false in @dexvraadminbot) turns them off. A
  // stale POST_BANNERS=0 env snapshot must never silently kill every channel
  // banner again (recurring incident: "setiap announce tidak ada banner").
  if (typeof g.enabled === "boolean") return g.enabled;
  return true;
}
async function setPostingEnabled(on) {
  const saved = loadJSONSync(CONFIG_FILE, {});
  saved._global = { ...(saved._global || {}), enabled: !!on };
  await saveJSON(CONFIG_FILE, saved);
  return !!on;
}
async function updateSettings(kind, settings) {
  const saved = loadJSONSync(CONFIG_FILE, {});
  // persist ONLY the admin's tweaks (over prior same-version tweaks) — never
  // bake defaults in, so future default retunes flow through untouched keys
  saved[kind] = { ...savedLayout(saved, kind), ...settings, layoutVersion: LAYOUT_VERSION };
  await saveJSON(CONFIG_FILE, saved);
  return { ...defaultsFor(kind), ...saved[kind] };
}
/** Drop every saved tweak for a kind — back to the defaults tuned for the
 *  bundled artwork. Cure for stale coordinates saved against older layouts. */
async function resetSettings(kind) {
  const saved = loadJSONSync(CONFIG_FILE, {});
  if (kind in saved) {
    delete saved[kind];
    await saveJSON(CONFIG_FILE, saved);
  }
  return { ...defaultsFor(kind) };
}
function getSettings(kind) {
  return loadConfig()[kind] || { ...defaultsFor(kind) };
}

/** Resolve the artwork to composite: admin upload → bundled default → null. */
function resolvePath(kind) {
  if (exists(uploadedPath(kind))) return uploadedPath(kind);
  if (exists(bundledPath(kind))) return bundledPath(kind);
  return null;
}
const hasTemplate = (kind) => !!resolvePath(kind);
const hasUploaded = (kind) => exists(uploadedPath(kind));

let CV = null; // lazy canvas (shared native lib with bannerRender)
function canvasLib() {
  if (CV === undefined) return null;
  if (CV) return CV;
  try {
    CV = require("@napi-rs/canvas");
    const FONTS = path.join(__dirname, "..", "assets", "fonts");
    const reg = (f, fam) => {
      const p = path.join(FONTS, f);
      if (fss.existsSync(p)) CV.GlobalFonts.registerFromPath(p, fam);
    };
    reg("Sora-800.ttf", "TplBold");
    reg("Sora-600.ttf", "TplSemi");
    reg("Sora-500.ttf", "TplReg");
  } catch (e) {
    log.warn(`[bannerTpl] canvas unavailable: ${e.message}`);
    CV = undefined;
    return null;
  }
  return CV;
}

/** Composite the kind's template with the token logo (+ optional text).
 *  Returns a PNG Buffer, or null when no template / any failure. */
async function compose(kind, logoBuffer, { symbol, name, chain, price, mcap, badge } = {}) {
  // Loud diagnostics: a null here silently downgrades channel posts to the raw
  // token logo, which reads as "the banner is broken" (live incident 2026-07).
  if (!hasTemplate(kind)) {
    log.warn(`[bannerTpl] no '${kind}' artwork found (${uploadedPath(kind)} / ${bundledPath(kind)}) — posting without template`);
    return null;
  }
  const cv = canvasLib();
  if (!cv) {
    log.warn(`[bannerTpl] @napi-rs/canvas unavailable — run 'npm ci' in bot/ on the server, then restart`);
    return null;
  }
  try {
    const cfg = getSettings(kind);
    const artPath = resolvePath(kind);
    if (!artPath) return null;
    const tpl = await cv.loadImage(artPath);
    // ALWAYS compose on the 2560×1280 reference canvas and stretch the artwork
    // to fill it. Admin uploads sent as Telegram PHOTOS arrive recompressed to
    // ~1280×640 — on that half-size canvas every layout coordinate (tuned for
    // 2560×1280) landed off-screen: empty ring, ticker clipped at the bottom
    // edge, invisible chips/badge (live incident 2026-07-19). Normalizing the
    // canvas makes layout coordinates mean the same thing for any upload size.
    const W = REF_W;
    const H = REF_H;
    const canvas = cv.createCanvas(W, H);
    const ctx = canvas.getContext("2d");
    ctx.drawImage(tpl, 0, 0, W, H);

    // Media slot: token logo circle-clipped into the ring, or (banner ads)
    // the advertiser's creative cover-fitted into a rounded rectangular frame.
    const isRect = cfg.slotShape === "rect";
    const sw = isRect ? Number(cfg.slotW) || 1680 : Number(cfg.logoSize) || BASE_DEFAULTS.logoSize;
    const sh = isRect ? Number(cfg.slotH) || 800 : sw;
    const lx = cfg.logoX === "center" ? (W - sw) / 2 : Number(cfg.logoX) || 0;
    const ly = cfg.logoY === "center" ? (H - sh) / 2 : Number(cfg.logoY) || 0;
    if (logoBuffer) {
      try {
        const img = await cv.loadImage(logoBuffer);
        ctx.save();
        ctx.beginPath();
        if (isRect) {
          const r = Math.min(40, sw / 2, sh / 2);
          ctx.moveTo(lx + r, ly);
          ctx.arcTo(lx + sw, ly, lx + sw, ly + sh, r);
          ctx.arcTo(lx + sw, ly + sh, lx, ly + sh, r);
          ctx.arcTo(lx, ly + sh, lx, ly, r);
          ctx.arcTo(lx, ly, lx + sw, ly, r);
        } else {
          ctx.arc(lx + sw / 2, ly + sh / 2, sw / 2, 0, Math.PI * 2);
        }
        ctx.closePath();
        ctx.clip();
        const s = Math.max(sw / img.width, sh / img.height);
        const w = img.width * s;
        const h = img.height * s;
        ctx.drawImage(img, lx + sw / 2 - w / 2, ly + sh / 2 - h / 2, w, h);
        ctx.restore();
        if (!isRect) {
          ctx.beginPath();
          ctx.arc(lx + sw / 2, ly + sh / 2, sw / 2 + 2, 0, Math.PI * 2);
          ctx.strokeStyle = "rgba(255,255,255,.55)";
          ctx.lineWidth = 3;
          ctx.stroke();
        }
      } catch (e) {
        log.debug(`[bannerTpl] media overlay: ${e.message}`); // artwork still posts
      }
    }

    // $TICKER + name overlay (position/size admin-tunable; off if artwork has
    // its own text or the admin prefers the art clean). Ticker renders with a
    // vertical white→tint gradient + soft accent glow — jewelry, not print.
    if (cfg.showText && symbol) {
      const ticker = `$${String(symbol).replace(/^\$+/, "").toUpperCase()}`;
      const fsz = Number(cfg.tickerFontSize) || 96;
      ctx.textBaseline = "middle";
      ctx.font = `800 ${fsz}px TplBold, sans-serif`;
      const tw = ctx.measureText(ticker).width;
      const tx = cfg.tickerX === "center" ? (W - tw) / 2 : Number(cfg.tickerX) || 0;
      const ty = cfg.tickerY === "center" ? H / 2 : Number(cfg.tickerY) || 0;
      // soft accent glow pass
      const glow = cfg.tickerGlow || "#4EE6A8";
      ctx.shadowColor = glow + "66";
      ctx.shadowBlur = Math.max(18, fsz * 0.3);
      ctx.shadowOffsetY = 0;
      const grad = ctx.createLinearGradient(0, ty - fsz * 0.55, 0, ty + fsz * 0.45);
      grad.addColorStop(0, "#FFFFFF");
      grad.addColorStop(0.72, cfg.tickerColor || "#FFFFFF");
      grad.addColorStop(1, "#BFE9DC");
      ctx.fillStyle = grad;
      ctx.fillText(ticker, tx, ty);
      // crisp second pass (kills glow muddiness on the glyph body)
      ctx.shadowColor = "rgba(0,0,0,.55)";
      ctx.shadowBlur = 6;
      ctx.shadowOffsetY = 2;
      ctx.fillText(ticker, tx, ty);
      if (name) {
        ctx.shadowColor = "rgba(0,0,0,.6)";
        ctx.shadowBlur = 6;
        ctx.shadowOffsetY = 2;
        ctx.font = `500 ${cfg.nameFontSize}px TplReg, sans-serif`;
        ctx.fillStyle = cfg.nameColor;
        const nx = cfg.tickerX === "center" ? (W - ctx.measureText(name).width) / 2 : tx;
        ctx.fillText(String(name).slice(0, 32), nx, ty + Number(cfg.nameOffsetY));
      }
      ctx.shadowColor = "transparent";
      ctx.shadowBlur = 0;
      ctx.shadowOffsetY = 0;
    }

    // Token meta chips under the ring: [CHAIN] [$price] [MC $x] — fills the
    // empty area beneath the hero with the data readers actually want.
    if (cfg.showText && cfg.slotShape !== "rect") {
      const vals = [chain, price && price !== "TBA" ? price : null, mcap ? `MC ${mcap}` : null]
        .map((v) => (v ? String(v) : null))
        .filter(Boolean);
      if (vals.length) {
        const fsz = Number(cfg.metaFontSize) || 38;
        const padX = fsz * 0.55;
        const gap = 18;
        const chipH = fsz * 1.9;
        ctx.font = `600 ${fsz}px TplSemi, TplReg, sans-serif`;
        const widths = vals.map((v) => ctx.measureText(v).width + padX * 2);
        const total = widths.reduce((a, b) => a + b, 0) + gap * (vals.length - 1);
        let x =
          cfg.metaX === "center" ? (W - total) / 2 : Number(cfg.metaX) || 210;
        const y = Number(cfg.metaY) || H - 152;
        for (let i = 0; i < vals.length; i++) {
          const w = widths[i];
          const r = chipH / 2;
          ctx.beginPath();
          ctx.moveTo(x + r, y);
          ctx.arcTo(x + w, y, x + w, y + chipH, r);
          ctx.arcTo(x + w, y + chipH, x, y + chipH, r);
          ctx.arcTo(x, y + chipH, x, y, r);
          ctx.arcTo(x, y, x + w, y, r);
          ctx.closePath();
          ctx.fillStyle = "rgba(255,255,255,.055)";
          ctx.fill();
          ctx.lineWidth = 2;
          ctx.strokeStyle = (cfg.tickerGlow || "#4EE6A8") + "55";
          ctx.stroke();
          ctx.fillStyle = i === 0 ? "#EAF6F2" : "#CFE4DE";
          ctx.textBaseline = "middle";
          ctx.fillText(vals[i], x + padX, y + chipH / 2 + 2);
          ctx.textBaseline = "alphabetic";
          x += w + gap;
        }
      }
    }

    // Pedestal badge — the small glass slab under the ring carries the tier
    // (listing) or the slot duration (trending) instead of sitting empty.
    if (badge && cfg.slotShape !== "rect") {
      const bfs = Number(cfg.badgeFontSize) || 30;
      ctx.font = `600 ${bfs}px TplSemi, TplReg, sans-serif`;
      ctx.letterSpacing = "4px";
      const btext = String(badge).toUpperCase().slice(0, 24);
      const bw = ctx.measureText(btext).width;
      const bx = (Number(cfg.badgeX) || W - 460) - bw / 2;
      const by = Number(cfg.badgeY) || H - 278;
      ctx.textBaseline = "middle";
      ctx.shadowColor = "rgba(0,0,0,.6)";
      ctx.shadowBlur = 6;
      ctx.shadowOffsetY = 1;
      ctx.fillStyle = "#D9F2EA";
      ctx.fillText(btext, bx, by);
      ctx.shadowColor = "transparent";
      ctx.shadowBlur = 0;
      ctx.shadowOffsetY = 0;
      ctx.letterSpacing = "0px";
      ctx.textBaseline = "alphabetic";
    }

    return canvas.toBuffer("image/png");
  } catch (e) {
    log.warn(`[bannerTpl] compose(${kind}) failed: ${e.message}`);
    return null;
  }
}

/** One-line boot report so pm2 logs show the banner pipeline's health without
 *  needing a live purchase: canvas availability + which artwork each kind
 *  resolves to (uploaded / bundled / MISSING). */
function selfCheck() {
  const canvas = canvasLib() ? "OK" : "MISSING (run 'npm ci' in bot/)";
  const art = KINDS.map((k) => {
    const state = hasUploaded(k) ? "uploaded" : exists(bundledPath(k)) ? "bundled" : "MISSING";
    return `${k}=${state}`;
  }).join(" ");
  const line = `[bannerTpl] selfcheck: canvas=${canvas} artwork: ${art}`;
  if (canvas === "OK" && !art.includes("MISSING")) log.info(line);
  else log.warn(`${line} — channel posts will degrade until this is fixed`);
  return line;
}

async function saveTemplate(kind, buffer) {
  await fss.promises.mkdir(DATA_DIR, { recursive: true });
  await fss.promises.writeFile(uploadedPath(kind), buffer);
}
/** Remove the admin upload — the bundled default artwork takes over again. */
async function removeTemplate(kind) {
  try {
    await fss.promises.unlink(uploadedPath(kind));
  } catch {
    /* already gone */
  }
}

module.exports = {
  KINDS,
  compose,
  selfCheck,
  postingEnabled,
  setPostingEnabled,
  hasTemplate,
  hasUploaded,
  saveTemplate,
  removeTemplate,
  mediaOverride,
  saveMedia,
  removeMedia,
  hasMedia,
  getSettings,
  updateSettings,
  resetSettings,
  resolvePath,
  DEFAULTS,
  defaultsFor,
};
