// Fourtis-style banner TEMPLATE compositor. An admin uploads a designed
// artwork (illustration/3D mascot/etc — the thing code can't draw) via
// @dexvraadminbot; every listing/trending channel post then composites the
// token's logo into the artwork's logo spot (circle-clipped) plus an optional
// $TICKER + name overlay. This is exactly how fourtis produces the banners the
// operator considers good — the art is designed once, the code only pastes.
//
// No template uploaded → compose() returns null and callers fall back to the
// programmatic dynamic banner (bannerRender.js). Never throws.
const path = require("node:path");
const fss = require("node:fs");
const { loadJSONSync, saveJSON, DATA_DIR } = require("./helpers/persist");
const log = require("./helpers/logger");

const CONFIG_FILE = "bannerTemplate.json";
const KINDS = ["listing", "trending", "banner"];
// Admin-uploaded artwork (wins) lives in DATA_DIR; a bundled default artwork
// ships in assets/ (generated by scripts/gen-artwork.mjs) so banners look
// designed out-of-the-box. BANNER_BUNDLED_DIR is overridable for tests.
const uploadedPath = (kind) => path.join(DATA_DIR, `banner-template-${kind}.png`);
const BUNDLED_DIR = process.env.BANNER_BUNDLED_DIR || path.join(__dirname, "..", "assets");
const bundledPath = (kind) => path.join(BUNDLED_DIR, `banner-artwork-${kind}.png`);

const exists = (p) => {
  try {
    return fss.existsSync(p) && fss.statSync(p).size > 0;
  } catch {
    return false;
  }
};

// Defaults are tuned for the BUNDLED artworks (2560×1280). listing/trending:
// circular logo spot in the glowing ring + $TICKER/name under the status pill.
// banner (ads): a rectangular slot in the glass frame for the advertiser's
// creative, no text overlay (the creative speaks for itself).
const BASE_DEFAULTS = {
  slotShape: "circle", // "circle" (token logo) | "rect" (ad creative)
  logoSize: 420, // circle: diameter of the clipped logo
  logoX: 1890, // number | "center" — top-left of the slot
  logoY: 410,
  slotW: 1680, // rect: slot width/height
  slotH: 800,
  showText: true, // draw $TICKER + name overlay
  tickerFontSize: 96,
  tickerX: 210, // number | "center"
  tickerY: 650,
  tickerColor: "#FFFFFF",
  nameFontSize: 48,
  nameColor: "#B8CCC8",
  nameOffsetY: 100,
};
const KIND_DEFAULTS = {
  listing: { ...BASE_DEFAULTS, tickerGlow: "#4EE6A8" },
  trending: { ...BASE_DEFAULTS, tickerGlow: "#38D8F0" },
  banner: { ...BASE_DEFAULTS, slotShape: "rect", logoX: 836, logoY: 296, slotW: 1548, slotH: 760, showText: false },
};
const defaultsFor = (kind) => KIND_DEFAULTS[kind] || BASE_DEFAULTS;
const DEFAULTS = BASE_DEFAULTS; // back-compat export

function loadConfig() {
  const saved = loadJSONSync(CONFIG_FILE, {});
  const out = {};
  for (const k of KINDS) out[k] = { ...defaultsFor(k), ...(saved[k] || {}) };
  return out;
}
async function updateSettings(kind, settings) {
  const saved = loadJSONSync(CONFIG_FILE, {});
  saved[kind] = { ...defaultsFor(kind), ...(saved[kind] || {}), ...settings };
  await saveJSON(CONFIG_FILE, saved);
  return saved[kind];
}
function getSettings(kind) {
  return loadConfig()[kind] || { ...defaultsFor(kind) };
}

/** Resolve the artwork to composite: admin upload → bundled default → null. */
function resolvePath(kind) {
  if (exists(uploadedPath(kind))) return uploadedPath(kind);
  if (exists(bundledPath(kind))) return bundledPath(kind);
  return null;
}
const hasTemplate = (kind) => !!resolvePath(kind);
const hasUploaded = (kind) => exists(uploadedPath(kind));

let CV = null; // lazy canvas (shared native lib with bannerRender)
function canvasLib() {
  if (CV === undefined) return null;
  if (CV) return CV;
  try {
    CV = require("@napi-rs/canvas");
    const FONTS = path.join(__dirname, "..", "assets", "fonts");
    const reg = (f, fam) => {
      const p = path.join(FONTS, f);
      if (fss.existsSync(p)) CV.GlobalFonts.registerFromPath(p, fam);
    };
    reg("Sora-800.ttf", "TplBold");
    reg("Sora-500.ttf", "TplReg");
  } catch (e) {
    log.warn(`[bannerTpl] canvas unavailable: ${e.message}`);
    CV = undefined;
    return null;
  }
  return CV;
}

/** Composite the kind's template with the token logo (+ optional text).
 *  Returns a PNG Buffer, or null when no template / any failure. */
async function compose(kind, logoBuffer, { symbol, name } = {}) {
  if (!hasTemplate(kind)) return null;
  const cv = canvasLib();
  if (!cv) return null;
  try {
    const cfg = getSettings(kind);
    const artPath = resolvePath(kind);
    if (!artPath) return null;
    const tpl = await cv.loadImage(artPath);
    const W = tpl.width;
    const H = tpl.height;
    const canvas = cv.createCanvas(W, H);
    const ctx = canvas.getContext("2d");
    ctx.drawImage(tpl, 0, 0, W, H);

    // Media slot: token logo circle-clipped into the ring, or (banner ads)
    // the advertiser's creative cover-fitted into a rounded rectangular frame.
    const isRect = cfg.slotShape === "rect";
    const sw = isRect ? Number(cfg.slotW) || 1680 : Number(cfg.logoSize) || BASE_DEFAULTS.logoSize;
    const sh = isRect ? Number(cfg.slotH) || 800 : sw;
    const lx = cfg.logoX === "center" ? (W - sw) / 2 : Number(cfg.logoX) || 0;
    const ly = cfg.logoY === "center" ? (H - sh) / 2 : Number(cfg.logoY) || 0;
    if (logoBuffer) {
      try {
        const img = await cv.loadImage(logoBuffer);
        ctx.save();
        ctx.beginPath();
        if (isRect) {
          const r = Math.min(40, sw / 2, sh / 2);
          ctx.moveTo(lx + r, ly);
          ctx.arcTo(lx + sw, ly, lx + sw, ly + sh, r);
          ctx.arcTo(lx + sw, ly + sh, lx, ly + sh, r);
          ctx.arcTo(lx, ly + sh, lx, ly, r);
          ctx.arcTo(lx, ly, lx + sw, ly, r);
        } else {
          ctx.arc(lx + sw / 2, ly + sh / 2, sw / 2, 0, Math.PI * 2);
        }
        ctx.closePath();
        ctx.clip();
        const s = Math.max(sw / img.width, sh / img.height);
        const w = img.width * s;
        const h = img.height * s;
        ctx.drawImage(img, lx + sw / 2 - w / 2, ly + sh / 2 - h / 2, w, h);
        ctx.restore();
        if (!isRect) {
          ctx.beginPath();
          ctx.arc(lx + sw / 2, ly + sh / 2, sw / 2 + 2, 0, Math.PI * 2);
          ctx.strokeStyle = "rgba(255,255,255,.55)";
          ctx.lineWidth = 3;
          ctx.stroke();
        }
      } catch (e) {
        log.debug(`[bannerTpl] media overlay: ${e.message}`); // artwork still posts
      }
    }

    // $TICKER + name overlay (position/size admin-tunable; off if artwork has
    // its own text or the admin prefers the art clean). Ticker renders with a
    // vertical white→tint gradient + soft accent glow — jewelry, not print.
    if (cfg.showText && symbol) {
      const ticker = `$${String(symbol).replace(/^\$+/, "").toUpperCase()}`;
      const fsz = Number(cfg.tickerFontSize) || 96;
      ctx.textBaseline = "middle";
      ctx.font = `800 ${fsz}px TplBold, sans-serif`;
      const tw = ctx.measureText(ticker).width;
      const tx = cfg.tickerX === "center" ? (W - tw) / 2 : Number(cfg.tickerX) || 0;
      const ty = cfg.tickerY === "center" ? H / 2 : Number(cfg.tickerY) || 0;
      // soft accent glow pass
      const glow = cfg.tickerGlow || "#4EE6A8";
      ctx.shadowColor = glow + "66";
      ctx.shadowBlur = Math.max(18, fsz * 0.3);
      ctx.shadowOffsetY = 0;
      const grad = ctx.createLinearGradient(0, ty - fsz * 0.55, 0, ty + fsz * 0.45);
      grad.addColorStop(0, "#FFFFFF");
      grad.addColorStop(0.72, cfg.tickerColor || "#FFFFFF");
      grad.addColorStop(1, "#BFE9DC");
      ctx.fillStyle = grad;
      ctx.fillText(ticker, tx, ty);
      // crisp second pass (kills glow muddiness on the glyph body)
      ctx.shadowColor = "rgba(0,0,0,.55)";
      ctx.shadowBlur = 6;
      ctx.shadowOffsetY = 2;
      ctx.fillText(ticker, tx, ty);
      if (name) {
        ctx.shadowColor = "rgba(0,0,0,.6)";
        ctx.shadowBlur = 6;
        ctx.shadowOffsetY = 2;
        ctx.font = `500 ${cfg.nameFontSize}px TplReg, sans-serif`;
        ctx.fillStyle = cfg.nameColor;
        const nx = cfg.tickerX === "center" ? (W - ctx.measureText(name).width) / 2 : tx;
        ctx.fillText(String(name).slice(0, 32), nx, ty + Number(cfg.nameOffsetY));
      }
      ctx.shadowColor = "transparent";
      ctx.shadowBlur = 0;
      ctx.shadowOffsetY = 0;
    }

    return canvas.toBuffer("image/png");
  } catch (e) {
    log.warn(`[bannerTpl] compose(${kind}) failed: ${e.message}`);
    return null;
  }
}

async function saveTemplate(kind, buffer) {
  await fss.promises.mkdir(DATA_DIR, { recursive: true });
  await fss.promises.writeFile(uploadedPath(kind), buffer);
}
/** Remove the admin upload — the bundled default artwork takes over again. */
async function removeTemplate(kind) {
  try {
    await fss.promises.unlink(uploadedPath(kind));
  } catch {
    /* already gone */
  }
}

module.exports = {
  KINDS,
  compose,
  hasTemplate,
  hasUploaded,
  saveTemplate,
  removeTemplate,
  getSettings,
  updateSettings,
  resolvePath,
  DEFAULTS,
  defaultsFor,
};
